# Generated by Django 4.1.7 on 2023-03-08 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(default=None, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(default=None, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProducerModel',
            fields=[
                ('producer_id', models.AutoField(primary_key=True, serialize=False)),
                ('producer_name', models.CharField(default=None, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EanDeviceModel',
            fields=[
                ('ean_device_id', models.AutoField(primary_key=True, serialize=False)),
                ('ean', models.CharField(default=None, max_length=50, unique=True)),
                ('model', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_api.categorymodel')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_api.producermodel')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=10000)),
                ('quantity', models.IntegerField(default=None)),
                ('condition', models.CharField(default=None, max_length=255)),
                ('status', models.CharField(default=None, max_length=255)),
                ('date_added', models.DateField(default=None)),
                ('qr_code', models.CharField(default=None, max_length=255)),
                ('returned', models.BooleanField(default=False)),
                ('ean_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_api.eandevicemodel')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceHistoryModel',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_api.devicemodel')),
            ],
        ),
    ]
