# Generated by Django 3.2.18 on 2023-03-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
