# Generated by Django 3.2.18 on 2023-03-08 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymodel',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='locationmodel',
            old_name='location_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='producermodel',
            old_name='producer_name',
            new_name='name',
        ),
    ]
